// Mocks generated by Mockito 5.4.6 from annotations
// in cine_book/test/services/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:cine_book/api/api_client.dart' as _i8;
import 'package:cine_book/models/booking_models.dart' as _i5;
import 'package:cine_book/models/movie.dart' as _i4;
import 'package:cine_book/models/notification_preferences.dart' as _i6;
import 'package:cine_book/models/paginated_response.dart' as _i3;
import 'package:cine_book/models/review.dart' as _i10;
import 'package:cine_book/models/showtime.dart' as _i11;
import 'package:cine_book/services/secure_storage_service.dart' as _i12;
import 'package:dio/dio.dart' as _i2;
import 'package:google_sign_in/google_sign_in.dart' as _i7;
import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart'
    as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOptions_1 extends _i1.SmartFake implements _i2.Options {
  _FakeOptions_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2<T1> extends _i1.SmartFake implements _i2.Response<T1> {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedResponse_3<T> extends _i1.SmartFake
    implements _i3.PaginatedResponse<T> {
  _FakePaginatedResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovie_4 extends _i1.SmartFake implements _i4.Movie {
  _FakeMovie_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSeatMap_5 extends _i1.SmartFake implements _i5.SeatMap {
  _FakeSeatMap_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHoldResponse_6 extends _i1.SmartFake implements _i5.HoldResponse {
  _FakeHoldResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBookingResponse_7 extends _i1.SmartFake
    implements _i5.BookingResponse {
  _FakeBookingResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBookingDetails_8 extends _i1.SmartFake
    implements _i5.BookingDetails {
  _FakeBookingDetails_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBookingQr_9 extends _i1.SmartFake implements _i5.BookingQr {
  _FakeBookingQr_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCancelBookingResponse_10 extends _i1.SmartFake
    implements _i5.CancelBookingResponse {
  _FakeCancelBookingResponse_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentStatusResult_11 extends _i1.SmartFake
    implements _i5.PaymentStatusResult {
  _FakePaymentStatusResult_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValidationResult_12 extends _i1.SmartFake
    implements _i5.ValidationResult {
  _FakeValidationResult_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationPreferences_13 extends _i1.SmartFake
    implements _i6.NotificationPreferences {
  _FakeNotificationPreferences_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoogleSignInAuthentication_14 extends _i1.SmartFake
    implements _i7.GoogleSignInAuthentication {
  _FakeGoogleSignInAuthentication_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [APIClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAPIClient extends _i1.Mock implements _i8.APIClient {
  MockAPIClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);

  @override
  set onUnauthorized(dynamic Function()? value) => super.noSuchMethod(
    Invocation.setter(#onUnauthorized, value),
    returnValueForMissingStub: null,
  );

  @override
  void updateBaseUrl(String? baseUrl) => super.noSuchMethod(
    Invocation.method(#updateBaseUrl, [baseUrl]),
    returnValueForMissingStub: null,
  );

  @override
  _i2.Options createStandardOptions({
    Map<String, dynamic>? headers,
    _i2.ResponseType? responseType,
    String? contentType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createStandardOptions, [], {
              #headers: headers,
              #responseType: responseType,
              #contentType: contentType,
            }),
            returnValue: _FakeOptions_1(
              this,
              Invocation.method(#createStandardOptions, [], {
                #headers: headers,
                #responseType: responseType,
                #contentType: contentType,
              }),
            ),
          )
          as _i2.Options);

  @override
  _i2.Options createPaymentOptions({
    Map<String, dynamic>? headers,
    _i2.ResponseType? responseType,
    String? contentType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPaymentOptions, [], {
              #headers: headers,
              #responseType: responseType,
              #contentType: contentType,
            }),
            returnValue: _FakeOptions_1(
              this,
              Invocation.method(#createPaymentOptions, [], {
                #headers: headers,
                #responseType: responseType,
                #contentType: contentType,
              }),
            ),
          )
          as _i2.Options);

  @override
  _i9.Future<_i2.Response<T>> get<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i9.Future<_i2.Response<T>>.value(
              _FakeResponse_2<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i2.Response<T>> post<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i9.Future<_i2.Response<T>>.value(
              _FakeResponse_2<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i2.Response<T>> postPayment<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postPayment,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i9.Future<_i2.Response<T>>.value(
              _FakeResponse_2<T>(
                this,
                Invocation.method(
                  #postPayment,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i2.Response<T>> put<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i9.Future<_i2.Response<T>>.value(
              _FakeResponse_2<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i2.Response<T>> patch<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i9.Future<_i2.Response<T>>.value(
              _FakeResponse_2<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i2.Response<T>> delete<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i9.Future<_i2.Response<T>>.value(
              _FakeResponse_2<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i3.PaginatedResponse<_i4.Movie>> getMovies({
    String? search,
    String? genre,
    String? status,
    int? page = 1,
    int? pageSize = 20,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMovies, [], {
              #search: search,
              #genre: genre,
              #status: status,
              #page: page,
              #pageSize: pageSize,
              #cancelToken: cancelToken,
            }),
            returnValue: _i9.Future<_i3.PaginatedResponse<_i4.Movie>>.value(
              _FakePaginatedResponse_3<_i4.Movie>(
                this,
                Invocation.method(#getMovies, [], {
                  #search: search,
                  #genre: genre,
                  #status: status,
                  #page: page,
                  #pageSize: pageSize,
                  #cancelToken: cancelToken,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.PaginatedResponse<_i4.Movie>>);

  @override
  _i9.Future<_i4.Movie> getMovieDetails(
    String? movieId, {
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMovieDetails,
              [movieId],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i9.Future<_i4.Movie>.value(
              _FakeMovie_4(
                this,
                Invocation.method(
                  #getMovieDetails,
                  [movieId],
                  {#cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i9.Future<_i4.Movie>);

  @override
  _i9.Future<_i3.PaginatedResponse<_i10.Review>> getMovieReviews(
    String? movieId, {
    int? page = 1,
    int? pageSize = 20,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMovieReviews,
              [movieId],
              {#page: page, #pageSize: pageSize, #cancelToken: cancelToken},
            ),
            returnValue: _i9.Future<_i3.PaginatedResponse<_i10.Review>>.value(
              _FakePaginatedResponse_3<_i10.Review>(
                this,
                Invocation.method(
                  #getMovieReviews,
                  [movieId],
                  {#page: page, #pageSize: pageSize, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i9.Future<_i3.PaginatedResponse<_i10.Review>>);

  @override
  _i9.Future<List<_i11.Showtime>> getShowtimes(
    String? movieId, {
    DateTime? date,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getShowtimes,
              [movieId],
              {#date: date, #cancelToken: cancelToken},
            ),
            returnValue: _i9.Future<List<_i11.Showtime>>.value(
              <_i11.Showtime>[],
            ),
          )
          as _i9.Future<List<_i11.Showtime>>);

  @override
  _i9.Future<_i5.SeatMap> getSeats(String? showtimeId) =>
      (super.noSuchMethod(
            Invocation.method(#getSeats, [showtimeId]),
            returnValue: _i9.Future<_i5.SeatMap>.value(
              _FakeSeatMap_5(this, Invocation.method(#getSeats, [showtimeId])),
            ),
          )
          as _i9.Future<_i5.SeatMap>);

  @override
  _i9.Future<_i5.HoldResponse> holdSeats(
    String? showtimeId,
    List<String>? seatCodes, {
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #holdSeats,
              [showtimeId, seatCodes],
              {#userId: userId},
            ),
            returnValue: _i9.Future<_i5.HoldResponse>.value(
              _FakeHoldResponse_6(
                this,
                Invocation.method(
                  #holdSeats,
                  [showtimeId, seatCodes],
                  {#userId: userId},
                ),
              ),
            ),
          )
          as _i9.Future<_i5.HoldResponse>);

  @override
  _i9.Future<List<_i5.FoodCombo>> getFoodCombos() =>
      (super.noSuchMethod(
            Invocation.method(#getFoodCombos, []),
            returnValue: _i9.Future<List<_i5.FoodCombo>>.value(
              <_i5.FoodCombo>[],
            ),
          )
          as _i9.Future<List<_i5.FoodCombo>>);

  @override
  _i9.Future<_i5.BookingResponse> createBooking(
    _i5.CreateBookingRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createBooking, [request]),
            returnValue: _i9.Future<_i5.BookingResponse>.value(
              _FakeBookingResponse_7(
                this,
                Invocation.method(#createBooking, [request]),
              ),
            ),
          )
          as _i9.Future<_i5.BookingResponse>);

  @override
  _i9.Future<_i5.BookingDetails> getBookingDetails(String? bookingId) =>
      (super.noSuchMethod(
            Invocation.method(#getBookingDetails, [bookingId]),
            returnValue: _i9.Future<_i5.BookingDetails>.value(
              _FakeBookingDetails_8(
                this,
                Invocation.method(#getBookingDetails, [bookingId]),
              ),
            ),
          )
          as _i9.Future<_i5.BookingDetails>);

  @override
  _i9.Future<List<_i5.BookingDetails>> getUserBookings(
    String? userId, {
    String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserBookings, [userId], {#status: status}),
            returnValue: _i9.Future<List<_i5.BookingDetails>>.value(
              <_i5.BookingDetails>[],
            ),
          )
          as _i9.Future<List<_i5.BookingDetails>>);

  @override
  _i9.Future<_i5.BookingQr> getBookingQr(String? bookingId) =>
      (super.noSuchMethod(
            Invocation.method(#getBookingQr, [bookingId]),
            returnValue: _i9.Future<_i5.BookingQr>.value(
              _FakeBookingQr_9(
                this,
                Invocation.method(#getBookingQr, [bookingId]),
              ),
            ),
          )
          as _i9.Future<_i5.BookingQr>);

  @override
  _i9.Future<_i5.CancelBookingResponse> cancelBooking(
    String? bookingId, {
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cancelBooking, [bookingId], {#userId: userId}),
            returnValue: _i9.Future<_i5.CancelBookingResponse>.value(
              _FakeCancelBookingResponse_10(
                this,
                Invocation.method(
                  #cancelBooking,
                  [bookingId],
                  {#userId: userId},
                ),
              ),
            ),
          )
          as _i9.Future<_i5.CancelBookingResponse>);

  @override
  _i9.Future<_i5.PaymentStatusResult> getPaymentStatus(String? bookingId) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentStatus, [bookingId]),
            returnValue: _i9.Future<_i5.PaymentStatusResult>.value(
              _FakePaymentStatusResult_11(
                this,
                Invocation.method(#getPaymentStatus, [bookingId]),
              ),
            ),
          )
          as _i9.Future<_i5.PaymentStatusResult>);

  @override
  _i9.Future<_i5.ValidationResult> validateTicket(
    String? bookingId,
    String? expectedShowtimeId, {
    String? staffId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #validateTicket,
              [bookingId, expectedShowtimeId],
              {#staffId: staffId},
            ),
            returnValue: _i9.Future<_i5.ValidationResult>.value(
              _FakeValidationResult_12(
                this,
                Invocation.method(
                  #validateTicket,
                  [bookingId, expectedShowtimeId],
                  {#staffId: staffId},
                ),
              ),
            ),
          )
          as _i9.Future<_i5.ValidationResult>);

  @override
  _i9.Future<List<_i5.BookingDetails>> searchBookings({
    String? bookingId,
    String? customerName,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchBookings, [], {
              #bookingId: bookingId,
              #customerName: customerName,
              #cancelToken: cancelToken,
            }),
            returnValue: _i9.Future<List<_i5.BookingDetails>>.value(
              <_i5.BookingDetails>[],
            ),
          )
          as _i9.Future<List<_i5.BookingDetails>>);

  @override
  _i9.Future<void> registerDevice({
    required String? userId,
    required String? deviceToken,
    required String? platform,
    String? deviceModel,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerDevice, [], {
              #userId: userId,
              #deviceToken: deviceToken,
              #platform: platform,
              #deviceModel: deviceModel,
              #cancelToken: cancelToken,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> unregisterDevice({
    required String? userId,
    required String? deviceToken,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#unregisterDevice, [], {
              #userId: userId,
              #deviceToken: deviceToken,
              #cancelToken: cancelToken,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i6.NotificationPreferences> getNotificationPreferences(
    String? userId, {
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getNotificationPreferences,
              [userId],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i9.Future<_i6.NotificationPreferences>.value(
              _FakeNotificationPreferences_13(
                this,
                Invocation.method(
                  #getNotificationPreferences,
                  [userId],
                  {#cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i9.Future<_i6.NotificationPreferences>);

  @override
  _i9.Future<void> updateNotificationPreferences(
    String? userId,
    _i6.NotificationPreferences? preferences, {
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateNotificationPreferences,
              [userId, preferences],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i12.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<void> saveAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccessToken, [token]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> saveRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveRefreshToken, [token]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> saveTokenExpiry(DateTime? expiryTime) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokenExpiry, [expiryTime]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<DateTime?> getTokenExpiry() =>
      (super.noSuchMethod(
            Invocation.method(#getTokenExpiry, []),
            returnValue: _i9.Future<DateTime?>.value(),
          )
          as _i9.Future<DateTime?>);

  @override
  _i9.Future<bool> hasAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#hasAccessToken, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> isTokenExpired() =>
      (super.noSuchMethod(
            Invocation.method(#isTokenExpired, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> clearTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearTokens, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> saveDeviceToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveDeviceToken, [token]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String?> getDeviceToken() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceToken, []),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<bool> hasDeviceTokenChanged(String? currentToken) =>
      (super.noSuchMethod(
            Invocation.method(#hasDeviceTokenChanged, [currentToken]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> clearDeviceToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearDeviceToken, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [GoogleSignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignIn extends _i1.Mock implements _i7.GoogleSignIn {
  MockGoogleSignIn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.SignInOption get signInOption =>
      (super.noSuchMethod(
            Invocation.getter(#signInOption),
            returnValue: _i13.SignInOption.standard,
          )
          as _i13.SignInOption);

  @override
  List<String> get scopes =>
      (super.noSuchMethod(Invocation.getter(#scopes), returnValue: <String>[])
          as List<String>);

  @override
  bool get forceCodeForRefreshToken =>
      (super.noSuchMethod(
            Invocation.getter(#forceCodeForRefreshToken),
            returnValue: false,
          )
          as bool);

  @override
  _i9.Stream<_i7.GoogleSignInAccount?> get onCurrentUserChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onCurrentUserChanged),
            returnValue: _i9.Stream<_i7.GoogleSignInAccount?>.empty(),
          )
          as _i9.Stream<_i7.GoogleSignInAccount?>);

  @override
  _i9.Future<_i7.GoogleSignInAccount?> signInSilently({
    bool? suppressErrors = true,
    bool? reAuthenticate = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInSilently, [], {
              #suppressErrors: suppressErrors,
              #reAuthenticate: reAuthenticate,
            }),
            returnValue: _i9.Future<_i7.GoogleSignInAccount?>.value(),
          )
          as _i9.Future<_i7.GoogleSignInAccount?>);

  @override
  _i9.Future<bool> isSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isSignedIn, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<_i7.GoogleSignInAccount?> signIn() =>
      (super.noSuchMethod(
            Invocation.method(#signIn, []),
            returnValue: _i9.Future<_i7.GoogleSignInAccount?>.value(),
          )
          as _i9.Future<_i7.GoogleSignInAccount?>);

  @override
  _i9.Future<_i7.GoogleSignInAccount?> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i9.Future<_i7.GoogleSignInAccount?>.value(),
          )
          as _i9.Future<_i7.GoogleSignInAccount?>);

  @override
  _i9.Future<_i7.GoogleSignInAccount?> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i9.Future<_i7.GoogleSignInAccount?>.value(),
          )
          as _i9.Future<_i7.GoogleSignInAccount?>);

  @override
  _i9.Future<bool> requestScopes(List<String>? scopes) =>
      (super.noSuchMethod(
            Invocation.method(#requestScopes, [scopes]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> canAccessScopes(
    List<String>? scopes, {
    String? accessToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #canAccessScopes,
              [scopes],
              {#accessToken: accessToken},
            ),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);
}

/// A class which mocks [GoogleSignInAccount].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockGoogleSignInAccount extends _i1.Mock
    implements _i7.GoogleSignInAccount {
  MockGoogleSignInAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i14.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  _i9.Future<_i7.GoogleSignInAuthentication> get authentication =>
      (super.noSuchMethod(
            Invocation.getter(#authentication),
            returnValue: _i9.Future<_i7.GoogleSignInAuthentication>.value(
              _FakeGoogleSignInAuthentication_14(
                this,
                Invocation.getter(#authentication),
              ),
            ),
          )
          as _i9.Future<_i7.GoogleSignInAuthentication>);

  @override
  _i9.Future<Map<String, String>> get authHeaders =>
      (super.noSuchMethod(
            Invocation.getter(#authHeaders),
            returnValue: _i9.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i9.Future<Map<String, String>>);

  @override
  _i9.Future<void> clearAuthCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAuthCache, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [GoogleSignInAuthentication].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInAuthentication extends _i1.Mock
    implements _i7.GoogleSignInAuthentication {
  MockGoogleSignInAuthentication() {
    _i1.throwOnMissingStub(this);
  }
}
